# The routes of the project.
#
# Each route describes how an incoming URL is going
# to be processed by Platform.sh.

"http://www.{default}/":
    type: upstream
    upstream: "app:http"
    cache:
      # Causes initial redirect to be cached in browser. Disabling
      # until we have a better solution.
      #enabled: true
      enabled: false
      headers: []
      default_ttl: 60

"http://{default}/":
    type: redirect
    to: "http://www.{default}/"
